#############################################################################
# Makefile for building: NEW_VRK_GUI
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  New_VRK_GUI.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile New_VRK_GUI.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x050F00 -DUSE_OPENCV3 -DUSE_PYLON -DUSE_CUDA -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include/opencv4 -I/opt/pylon/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = NEW_VRK_GUI1.0.0
DISTDIR = /home/p27/kilobot_project/VRK/New_VRK_GUI/.tmp/NEW_VRK_GUI1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_features2d -lopencv_highgui -lopencv_calib3d -lopencv_flann -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lopencv_videoio -lopencv_imgcodecs -lopencv_aruco -lz -lopencv_cudawarping -lopencv_cudafeatures2d -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_cudaarithm -lzbar -L/opt/pylon/lib -lpylonbase -lpylonutility -lGenApi_gcc_v3_1_Basler_pylon -lGCBase_gcc_v3_1_Basler_pylon /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		arenaWindow.cpp \
		etc/publicvars.cpp \
		kilobotoverheadcontroller.cpp \
		ohc/calibrate.cpp \
		ohc/intelhex.cpp \
		ohc/serialconn.cpp \
		ohc/serialwin.cpp \
		qcustomplot.cpp \
		mainwindow.cpp \
		savevid_thread.cpp \
		tracker/detectQR.cpp \
		tracker/kilobot.cpp \
		tracker/kilobottracker.cpp \
		tracker/pylon.cpp \
		ui/geom/angle_deg.cpp \
		ui/geom/vector_2d.cpp \
		ui/mobileobject.cpp \
		ui/renderarea.cpp \
		ui/robot.cpp \
		ui/worldmodel.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_arenaWindow.cpp \
		moc_kilobotoverheadcontroller.cpp \
		moc_calibrate.cpp \
		moc_serialconn.cpp \
		moc_serialwin.cpp \
		moc_qcustomplot.cpp \
		moc_detectQR.cpp \
		moc_kilobot.cpp \
		moc_kilobottracker.cpp \
		moc_mobileobject.cpp \
		moc_renderarea.cpp \
		moc_robot.cpp
OBJECTS       = main.o \
		arenaWindow.o \
		publicvars.o \
		kilobotoverheadcontroller.o \
		calibrate.o \
		intelhex.o \
		serialconn.o \
		serialwin.o \
		qcustomplot.o \
		mainwindow.o \
		savevid_thread.o \
		detectQR.o \
		kilobot.o \
		kilobottracker.o \
		pylon.o \
		angle_deg.o \
		vector_2d.o \
		mobileobject.o \
		renderarea.o \
		robot.o \
		worldmodel.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_arenaWindow.o \
		moc_kilobotoverheadcontroller.o \
		moc_calibrate.o \
		moc_serialconn.o \
		moc_serialwin.o \
		moc_qcustomplot.o \
		moc_detectQR.o \
		moc_kilobot.o \
		moc_kilobottracker.o \
		moc_mobileobject.o \
		moc_renderarea.o \
		moc_robot.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		New_VRK_GUI.pro mainwindow.h \
		arenaWindow.h \
		etc/publicvars.h \
		kilobotoverheadcontroller.h \
		ohc/calibrate.h \
		ohc/intelhex.h \
		ohc/packet.h \
		ohc/serialconn.h \
		ohc/serialwin.h \
		qcustomplot.h \
		savevid_thread.h \
		tracker/detectQR.h \
		tracker/kilobot.h \
		tracker/kilobottracker.h \
		tracker/pylon.h \
		ui/geom/angle_deg.h \
		ui/geom/circle_2d.h \
		ui/geom/composite_region_2d.h \
		ui/geom/convex_hull.h \
		ui/geom/delaunay_triangulation.h \
		ui/geom/geom.h \
		ui/geom/line_2d.h \
		ui/geom/matrix_2d.h \
		ui/geom/polygon_2d.h \
		ui/geom/ray_2d.h \
		ui/geom/rect_2d.h \
		ui/geom/region_2d.h \
		ui/geom/sector_2d.h \
		ui/geom/segment_2d.h \
		ui/geom/size_2d.h \
		ui/geom/triangle_2d.h \
		ui/geom/triangulation.h \
		ui/geom/vector_2d.h \
		ui/geom/voronoi_diagram.h \
		ui/mobileobject.h \
		ui/renderarea.h \
		ui/robot.h \
		ui/worldmodel.h main.cpp \
		arenaWindow.cpp \
		etc/publicvars.cpp \
		kilobotoverheadcontroller.cpp \
		ohc/calibrate.cpp \
		ohc/intelhex.cpp \
		ohc/serialconn.cpp \
		ohc/serialwin.cpp \
		qcustomplot.cpp \
		mainwindow.cpp \
		savevid_thread.cpp \
		tracker/detectQR.cpp \
		tracker/kilobot.cpp \
		tracker/kilobottracker.cpp \
		tracker/pylon.cpp \
		ui/geom/angle_deg.cpp \
		ui/geom/vector_2d.cpp \
		ui/mobileobject.cpp \
		ui/renderarea.cpp \
		ui/robot.cpp \
		ui/worldmodel.cpp
QMAKE_TARGET  = NEW_VRK_GUI
DESTDIR       = 
TARGET        = NEW_VRK_GUI


first: all
####### Build rules

NEW_VRK_GUI: ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h ui_arenaWindow_copy.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: New_VRK_GUI.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		New_VRK_GUI.pro \
		resources.qrc
	$(QMAKE) -o Makefile New_VRK_GUI.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
New_VRK_GUI.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile New_VRK_GUI.pro -spec linux-g++

qmake_all: FORCE


all: Makefile NEW_VRK_GUI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h arenaWindow.h etc/publicvars.h kilobotoverheadcontroller.h ohc/calibrate.h ohc/intelhex.h ohc/packet.h ohc/serialconn.h ohc/serialwin.h qcustomplot.h savevid_thread.h tracker/detectQR.h tracker/kilobot.h tracker/kilobottracker.h tracker/pylon.h ui/geom/angle_deg.h ui/geom/circle_2d.h ui/geom/composite_region_2d.h ui/geom/convex_hull.h ui/geom/delaunay_triangulation.h ui/geom/geom.h ui/geom/line_2d.h ui/geom/matrix_2d.h ui/geom/polygon_2d.h ui/geom/ray_2d.h ui/geom/rect_2d.h ui/geom/region_2d.h ui/geom/sector_2d.h ui/geom/segment_2d.h ui/geom/size_2d.h ui/geom/triangle_2d.h ui/geom/triangulation.h ui/geom/vector_2d.h ui/geom/voronoi_diagram.h ui/mobileobject.h ui/renderarea.h ui/robot.h ui/worldmodel.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp arenaWindow.cpp etc/publicvars.cpp kilobotoverheadcontroller.cpp ohc/calibrate.cpp ohc/intelhex.cpp ohc/serialconn.cpp ohc/serialwin.cpp qcustomplot.cpp mainwindow.cpp savevid_thread.cpp tracker/detectQR.cpp tracker/kilobot.cpp tracker/kilobottracker.cpp tracker/pylon.cpp ui/geom/angle_deg.cpp ui/geom/vector_2d.cpp ui/mobileobject.cpp ui/renderarea.cpp ui/robot.cpp ui/worldmodel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui DynamicWidgets.ui arenaWindow.ui arenaWindow_copy.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		qrCode.qml \
		Files/KilobotHeter.png \
		Files/marker3.png \
		Files/col_dec_mak.jpg \
		Files/marker2.png \
		Files/marker1.png \
		Files/marker0.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_arenaWindow.cpp moc_kilobotoverheadcontroller.cpp moc_calibrate.cpp moc_serialconn.cpp moc_serialwin.cpp moc_qcustomplot.cpp moc_detectQR.cpp moc_kilobot.cpp moc_kilobottracker.cpp moc_mobileobject.cpp moc_renderarea.cpp moc_robot.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_arenaWindow.cpp moc_kilobotoverheadcontroller.cpp moc_calibrate.cpp moc_serialconn.cpp moc_serialwin.cpp moc_qcustomplot.cpp moc_detectQR.cpp moc_kilobot.cpp moc_kilobottracker.cpp moc_mobileobject.cpp moc_renderarea.cpp moc_robot.cpp
moc_mainwindow.cpp: mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevid_thread.h \
		tracker/kilobottracker.h \
		tracker/kilobot.h \
		kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_arenaWindow.cpp: arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include arenaWindow.h -o moc_arenaWindow.cpp

moc_kilobotoverheadcontroller.cpp: kilobotoverheadcontroller.h \
		tracker/kilobot.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include kilobotoverheadcontroller.h -o moc_kilobotoverheadcontroller.cpp

moc_calibrate.cpp: ohc/calibrate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ohc/calibrate.h -o moc_calibrate.cpp

moc_serialconn.cpp: ohc/serialconn.h \
		ohc/intelhex.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ohc/serialconn.h -o moc_serialconn.cpp

moc_serialwin.cpp: ohc/serialwin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ohc/serialwin.h -o moc_serialwin.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_detectQR.cpp: tracker/detectQR.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tracker/detectQR.h -o moc_detectQR.cpp

moc_kilobot.cpp: tracker/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tracker/kilobot.h -o moc_kilobot.cpp

moc_kilobottracker.cpp: tracker/kilobottracker.h \
		tracker/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include tracker/kilobottracker.h -o moc_kilobottracker.cpp

moc_mobileobject.cpp: ui/mobileobject.h \
		ui/position.h \
		ui/geom/geom.h \
		ui/geom/angle_deg.h \
		ui/geom/vector_2d.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/mobileobject.h -o moc_mobileobject.cpp

moc_renderarea.cpp: ui/renderarea.h \
		ui/worldmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/renderarea.h -o moc_renderarea.cpp

moc_robot.cpp: ui/robot.h \
		ui/mobileobject.h \
		ui/position.h \
		ui/geom/geom.h \
		ui/geom/angle_deg.h \
		ui/geom/vector_2d.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/p27/kilobot_project/VRK/New_VRK_GUI/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/p27/kilobot_project/VRK/New_VRK_GUI -I/usr/local/include/opencv4 -I/opt/pylon/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ui/robot.h -o moc_robot.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h ui_arenaWindow_copy.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h ui_arenaWindow_copy.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		qcustomplot.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_DynamicWidgets.h: DynamicWidgets.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DynamicWidgets.ui -o ui_DynamicWidgets.h

ui_arenaWindow.h: arenaWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic arenaWindow.ui -o ui_arenaWindow.h

ui_arenaWindow_copy.h: arenaWindow_copy.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic arenaWindow_copy.ui -o ui_arenaWindow_copy.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevid_thread.h \
		tracker/kilobottracker.h \
		tracker/kilobot.h \
		kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

arenaWindow.o: arenaWindow.cpp arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui_arenaWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arenaWindow.o arenaWindow.cpp

publicvars.o: etc/publicvars.cpp etc/publicvars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o publicvars.o etc/publicvars.cpp

kilobotoverheadcontroller.o: kilobotoverheadcontroller.cpp kilobotoverheadcontroller.h \
		tracker/kilobot.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		ohc/packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kilobotoverheadcontroller.o kilobotoverheadcontroller.cpp

calibrate.o: ohc/calibrate.cpp ohc/calibrate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrate.o ohc/calibrate.cpp

intelhex.o: ohc/intelhex.cpp ohc/intelhex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intelhex.o ohc/intelhex.cpp

serialconn.o: ohc/serialconn.cpp ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialconn.o ohc/serialconn.cpp

serialwin.o: ohc/serialwin.cpp ohc/serialwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialwin.o ohc/serialwin.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevid_thread.h \
		tracker/kilobottracker.h \
		tracker/kilobot.h \
		kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

savevid_thread.o: savevid_thread.cpp savevid_thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savevid_thread.o savevid_thread.cpp

detectQR.o: tracker/detectQR.cpp tracker/detectQR.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detectQR.o tracker/detectQR.cpp

kilobot.o: tracker/kilobot.cpp tracker/kilobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kilobot.o tracker/kilobot.cpp

kilobottracker.o: tracker/kilobottracker.cpp tracker/kilobottracker.h \
		tracker/kilobot.h \
		tracker/pylon.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kilobottracker.o tracker/kilobottracker.cpp

pylon.o: tracker/pylon.cpp tracker/pylon.h \
		/opt/pylon/include/pylon/InstantCamera.h \
		/opt/pylon/include/pylon/Platform.h \
		/opt/pylon/include/pylon/api_autoconf.h \
		/opt/pylon/include/pylon/stdinclude.h \
		/opt/pylon/include/Base/GCNamespace.h \
		/opt/pylon/include/GenICamVersion.h \
		/opt/pylon/include/_GenICamVersion.h \
		/opt/pylon/include/GenApi/GenApiNamespace.h \
		/opt/pylon/include/pylon/TypeMappings.h \
		/opt/pylon/include/Base/GCTypes.h \
		/opt/pylon/include/Base/GCString.h \
		/opt/pylon/include/Base/GCStringVector.h \
		/opt/pylon/include/Base/GCException.h \
		/opt/pylon/include/GenICamFwd.h \
		/opt/pylon/include/GenApi/Synch.h \
		/opt/pylon/include/GenApi/GenApiDll.h \
		/opt/pylon/include/pylon/PylonBase.h \
		/opt/pylon/include/pylon/ImageEventHandler.h \
		/opt/pylon/include/pylon/GrabResultPtr.h \
		/opt/pylon/include/pylon/GrabResultData.h \
		/opt/pylon/include/pylon/PixelType.h \
		/opt/pylon/include/pylon/PayloadType.h \
		/opt/pylon/include/pylon/Image.h \
		/opt/pylon/include/pylon/ConfigurationEventHandler.h \
		/opt/pylon/include/pylon/CameraEventHandler.h \
		/opt/pylon/include/GenApi/INode.h \
		/opt/pylon/include/GenApi/Types.h \
		/opt/pylon/include/GenApi/Autovector.h \
		/opt/pylon/include/GenApi/IBase.h \
		/opt/pylon/include/GenApi/Reference.h \
		/opt/pylon/include/GenApi/Container.h \
		/opt/pylon/include/pylon/BufferFactory.h \
		/opt/pylon/include/pylon/DeviceInfo.h \
		/opt/pylon/include/pylon/Info.h \
		/opt/pylon/include/pylon/WaitObject.h \
		/opt/pylon/include/pylon/Device.h \
		/opt/pylon/include/pylon/WaitObjects.h \
		/opt/pylon/include/pylon/EventAdapter.h \
		/opt/pylon/include/pylon/Callback.h \
		/opt/pylon/include/pylon/DeviceAccessMode.h \
		/opt/pylon/include/pylon/PylonVersionNumber.h \
		/opt/pylon/include/pylon/SfncVersion.h \
		/opt/pylon/include/pylon/PylonVersionInfo.h \
		/opt/pylon/include/GenApi/GenApi.h \
		/opt/pylon/include/Base/GCBase.h \
		/opt/pylon/include/Base/GCArray.h \
		/opt/pylon/include/Base/GCUtilities.h \
		/opt/pylon/include/Base/GCLinkage.h \
		/opt/pylon/include/Base/GCRTSSUtilities.h \
		/opt/pylon/include/GenApi/Pointer.h \
		/opt/pylon/include/GenApi/IEnumeration.h \
		/opt/pylon/include/GenApi/IEnumEntry.h \
		/opt/pylon/include/GenApi/IValue.h \
		/opt/pylon/include/GenApi/IFloat.h \
		/opt/pylon/include/GenApi/IInteger.h \
		/opt/pylon/include/GenApi/ICategory.h \
		/opt/pylon/include/GenApi/IRegister.h \
		/opt/pylon/include/GenApi/IBoolean.h \
		/opt/pylon/include/GenApi/IPort.h \
		/opt/pylon/include/GenApi/IPortRecorder.h \
		/opt/pylon/include/GenApi/IPortConstruct.h \
		/opt/pylon/include/GenApi/IChunkPort.h \
		/opt/pylon/include/GenApi/IString.h \
		/opt/pylon/include/GenApi/INodeMap.h \
		/opt/pylon/include/GenApi/IDestroy.h \
		/opt/pylon/include/GenApi/IDeviceInfo.h \
		/opt/pylon/include/GenApi/ISelector.h \
		/opt/pylon/include/GenApi/ICommand.h \
		/opt/pylon/include/GenApi/IUserData.h \
		/opt/pylon/include/GenApi/NodeMapRef.h \
		/opt/pylon/include/GenApi/NodeMapFactory.h \
		/opt/pylon/include/GenApi/GenApiVersion.h \
		/opt/pylon/include/GenApi/NodeCallback.h \
		/opt/pylon/include/GenApi/Persistence.h \
		/opt/pylon/include/GenApi/StructPort.h \
		/opt/pylon/include/GenApi/PortImpl.h \
		/opt/pylon/include/GenApi/SelectorSet.h \
		/opt/pylon/include/GenApi/ISelectorDigit.h \
		/opt/pylon/include/GenApi/GenApiLinkage.h \
		/opt/pylon/include/pylon/_InstantCameraParams.h \
		/opt/pylon/include/pylon/ParameterIncludes.h \
		/opt/pylon/include/pylon/ArrayParameter.h \
		/opt/pylon/include/pylon/Parameter.h \
		/opt/pylon/include/pylon/BooleanParameter.h \
		/opt/pylon/include/pylon/CommandParameter.h \
		/opt/pylon/include/pylon/EnumParameter.h \
		/opt/pylon/include/pylon/FloatParameter.h \
		/opt/pylon/include/pylon/IntegerParameter.h \
		/opt/pylon/include/pylon/StringParameter.h \
		/opt/pylon/include/pylon/EnumParameterT.h \
		/opt/pylon/include/pylon/ImageFormatConverter.h \
		/opt/pylon/include/pylon/PylonUtility.h \
		/opt/pylon/include/pylon/_ImageFormatConverterParams.h \
		/opt/pylon/include/pylon/ReusableImage.h \
		/opt/pylon/include/pylon/PylonImage.h \
		/opt/pylon/include/pylon/PylonImageBase.h \
		/opt/pylon/include/pylon/ImagePersistence.h \
		/opt/pylon/include/pylon/PixelData.h \
		/opt/pylon/include/pylon/PylonImageUserBufferEventHandler.h \
		/opt/pylon/include/pylon/PylonIncludes.h \
		/opt/pylon/include/pylon/PylonLinkage.h \
		/opt/pylon/include/pylon/TlInfo.h \
		/opt/pylon/include/pylon/DeviceClass.h \
		/opt/pylon/include/pylon/Container.h \
		/opt/pylon/include/pylon/InterfaceInfo.h \
		/opt/pylon/include/pylon/DeviceFactory.h \
		/opt/pylon/include/pylon/TransportLayer.h \
		/opt/pylon/include/pylon/Interface.h \
		/opt/pylon/include/pylon/TlFactory.h \
		/opt/pylon/include/pylon/StreamGrabber.h \
		/opt/pylon/include/pylon/Pixel.h \
		/opt/pylon/include/pylon/PixelTypeMapper.h \
		/opt/pylon/include/GenApi/IEnumerationT.h \
		/opt/pylon/include/GenApi/Compatibility.h \
		/opt/pylon/include/pylon/Result.h \
		/opt/pylon/include/pylon/ResultImage.h \
		/opt/pylon/include/pylon/PylonDataComponent.h \
		/opt/pylon/include/pylon/PylonDataContainer.h \
		/opt/pylon/include/pylon/ChunkParser.h \
		/opt/pylon/include/pylon/EventGrabber.h \
		/opt/pylon/include/pylon/EventGrabberProxy.h \
		/opt/pylon/include/pylon/NodeMapProxy.h \
		/opt/pylon/include/pylon/AcquireSingleFrameConfiguration.h \
		/opt/pylon/include/pylon/ConfigurationHelper.h \
		/opt/pylon/include/pylon/InstantCameraArray.h \
		/opt/pylon/include/pylon/AcquireContinuousConfiguration.h \
		/opt/pylon/include/pylon/SoftwareTriggerConfiguration.h \
		/opt/pylon/include/pylon/InstantInterface.h \
		/opt/pylon/include/pylon/_BaslerUniversalInterfaceParams.h \
		/opt/pylon/include/pylon/PylonUtilityIncludes.h \
		/opt/pylon/include/pylon/ImageDecompressor.h \
		/opt/pylon/include/pylon/FeaturePersistence.h \
		/opt/pylon/include/pylon/VideoWriter.h \
		/opt/pylon/include/pylon/_VideoWriterParams.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pylon.o tracker/pylon.cpp

angle_deg.o: ui/geom/angle_deg.cpp ui/geom/angle_deg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o angle_deg.o ui/geom/angle_deg.cpp

vector_2d.o: ui/geom/vector_2d.cpp ui/geom/vector_2d.h \
		ui/geom/angle_deg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector_2d.o ui/geom/vector_2d.cpp

mobileobject.o: ui/mobileobject.cpp ui/mobileobject.h \
		ui/position.h \
		ui/geom/geom.h \
		ui/geom/angle_deg.h \
		ui/geom/vector_2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mobileobject.o ui/mobileobject.cpp

renderarea.o: ui/renderarea.cpp ui/renderarea.h \
		ui/worldmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderarea.o ui/renderarea.cpp

robot.o: ui/robot.cpp ui/robot.h \
		ui/mobileobject.h \
		ui/position.h \
		ui/geom/geom.h \
		ui/geom/angle_deg.h \
		ui/geom/vector_2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robot.o ui/robot.cpp

worldmodel.o: ui/worldmodel.cpp ui/worldmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worldmodel.o ui/worldmodel.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_arenaWindow.o: moc_arenaWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_arenaWindow.o moc_arenaWindow.cpp

moc_kilobotoverheadcontroller.o: moc_kilobotoverheadcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobotoverheadcontroller.o moc_kilobotoverheadcontroller.cpp

moc_calibrate.o: moc_calibrate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrate.o moc_calibrate.cpp

moc_serialconn.o: moc_serialconn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialconn.o moc_serialconn.cpp

moc_serialwin.o: moc_serialwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialwin.o moc_serialwin.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_detectQR.o: moc_detectQR.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detectQR.o moc_detectQR.cpp

moc_kilobot.o: moc_kilobot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobot.o moc_kilobot.cpp

moc_kilobottracker.o: moc_kilobottracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobottracker.o moc_kilobottracker.cpp

moc_mobileobject.o: moc_mobileobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mobileobject.o moc_mobileobject.cpp

moc_renderarea.o: moc_renderarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderarea.o moc_renderarea.cpp

moc_robot.o: moc_robot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robot.o moc_robot.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

