#############################################################################
# Makefile for building: LARS
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  LARS.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile LARS.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DISABLE_DEPRECATED_BEFORE=0x050F00 -DUSE_OPENCV3 -DUSE_PYLON -DUSE_CUDA -DFOR_KILOBOT -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = LARS1.0.0
DISTDIR = /home/jetsi/projects/LARS/LARS/.tmp/LARS1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/local/lib/ -lopencv_core -lopencv_imgproc -lopencv_features2d -lopencv_highgui -lopencv_calib3d -lopencv_flann -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lopencv_videoio -lopencv_imgcodecs -lopencv_aruco -lz -ligraph -lopencv_cudawarping -lopencv_cudafeatures2d -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_cudaarithm -lzbar -lboost_system -L/opt/pylon/lib -lpylonbase -lpylonutility -lGenApi_gcc_v3_1_Basler_pylon -lGCBase_gcc_v3_1_Basler_pylon /usr/lib/aarch64-linux-gnu/libQt5PrintSupport.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Kilobot/kilobot.cpp \
		Kilobot/kilobotoverheadcontroller.cpp \
		arenaWindow.cpp \
		envbrain.cpp \
		etc/publicvars.cpp \
		ohc/calibrate.cpp \
		ohc/intelhex.cpp \
		ohc/serialconn.cpp \
		ohc/serialwin.cpp \
		qcustomplot.cpp \
		mainwindow.cpp \
		savevidthread.cpp \
		tracker/detectQR.cpp \
		tracker/pylon.cpp \
		tracker/robottracker.cpp \
		ui/geom/voronoiGenerator.cpp \
		ui/renderarea.cpp \
		ui/worldmodel.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_kilobot.cpp \
		moc_kilobotenvironment.cpp \
		moc_kilobotexperiment.cpp \
		moc_kilobotoverheadcontroller.cpp \
		moc_arenaWindow.cpp \
		moc_envbrain.cpp \
		moc_calibrate.cpp \
		moc_serialconn.cpp \
		moc_serialwin.cpp \
		moc_qcustomplot.cpp \
		moc_savevidthread.cpp \
		moc_detectQR.cpp \
		moc_robottracker.cpp \
		moc_renderarea.cpp
OBJECTS       = main.o \
		kilobot.o \
		kilobotoverheadcontroller.o \
		arenaWindow.o \
		envbrain.o \
		publicvars.o \
		calibrate.o \
		intelhex.o \
		serialconn.o \
		serialwin.o \
		qcustomplot.o \
		mainwindow.o \
		savevidthread.o \
		detectQR.o \
		pylon.o \
		robottracker.o \
		voronoiGenerator.o \
		renderarea.o \
		worldmodel.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_kilobot.o \
		moc_kilobotenvironment.o \
		moc_kilobotexperiment.o \
		moc_kilobotoverheadcontroller.o \
		moc_arenaWindow.o \
		moc_envbrain.o \
		moc_calibrate.o \
		moc_serialconn.o \
		moc_serialwin.o \
		moc_qcustomplot.o \
		moc_savevidthread.o \
		moc_detectQR.o \
		moc_robottracker.o \
		moc_renderarea.o
DIST          = pyTestClass.py \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LARS.pro mainwindow.h \
		Kilobot/kilobot.h \
		Kilobot/kilobotenvironment.h \
		Kilobot/kilobotexperiment.h \
		Kilobot/kilobotoverheadcontroller.h \
		arenaWindow.h \
		envbrain.h \
		etc/publicvars.h \
		ohc/calibrate.h \
		ohc/intelhex.h \
		ohc/packet.h \
		ohc/serialconn.h \
		ohc/serialwin.h \
		qcustomplot.h \
		savevidthread.h \
		tracker/detectQR.h \
		tracker/kilobot.h \
		tracker/pylon.h \
		tracker/robottracker.h \
		ui/geom/voronoiGenerator.h \
		ui/renderarea.h \
		ui/worldmodel.h main.cpp \
		Kilobot/kilobot.cpp \
		Kilobot/kilobotoverheadcontroller.cpp \
		arenaWindow.cpp \
		envbrain.cpp \
		etc/publicvars.cpp \
		ohc/calibrate.cpp \
		ohc/intelhex.cpp \
		ohc/serialconn.cpp \
		ohc/serialwin.cpp \
		qcustomplot.cpp \
		mainwindow.cpp \
		savevidthread.cpp \
		tracker/detectQR.cpp \
		tracker/pylon.cpp \
		tracker/robottracker.cpp \
		ui/geom/voronoiGenerator.cpp \
		ui/renderarea.cpp \
		ui/worldmodel.cpp
QMAKE_TARGET  = LARS
DESTDIR       = 
TARGET        = LARS


first: all
####### Build rules

LARS: ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LARS.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		LARS.pro \
		resources.qrc
	$(QMAKE) -o Makefile LARS.pro
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
LARS.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile LARS.pro

qmake_all: FORCE


all: Makefile LARS

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h Kilobot/kilobot.h Kilobot/kilobotenvironment.h Kilobot/kilobotexperiment.h Kilobot/kilobotoverheadcontroller.h arenaWindow.h envbrain.h etc/publicvars.h ohc/calibrate.h ohc/intelhex.h ohc/packet.h ohc/serialconn.h ohc/serialwin.h qcustomplot.h savevidthread.h tracker/detectQR.h tracker/kilobot.h tracker/pylon.h tracker/robottracker.h ui/geom/voronoiGenerator.h ui/renderarea.h ui/worldmodel.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp Kilobot/kilobot.cpp Kilobot/kilobotoverheadcontroller.cpp arenaWindow.cpp envbrain.cpp etc/publicvars.cpp ohc/calibrate.cpp ohc/intelhex.cpp ohc/serialconn.cpp ohc/serialwin.cpp qcustomplot.cpp mainwindow.cpp savevidthread.cpp tracker/detectQR.cpp tracker/pylon.cpp tracker/robottracker.cpp ui/geom/voronoiGenerator.cpp ui/renderarea.cpp ui/worldmodel.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui DynamicWidgets.ui arenaWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		qrCode.qml \
		Files/marker1.png \
		Files/arena_02.png \
		Files/marker2.png \
		Files/arena_03.png \
		Files/marker3.png \
		Files/arena_04.png \
		Files/empty_image.png \
		Files/arena_05.png \
		Files/webpage.png \
		Files/arena_06.png \
		Files/arena_07.png \
		Files/arena_08.png \
		Files/KilobotHeter.png \
		Files/centroid.png \
		Files/arena_white.png \
		Files/arena_image.png \
		Files/ball.png \
		Files/scioiNet.gif \
		Files/LARS_Logo.png \
		Files/SCIoI_Logo.png \
		Files/col_dec_mak.jpg \
		Files/psioi.png \
		Files/arena_01.png \
		Files/marker0.png
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_kilobot.cpp moc_kilobotenvironment.cpp moc_kilobotexperiment.cpp moc_kilobotoverheadcontroller.cpp moc_arenaWindow.cpp moc_envbrain.cpp moc_calibrate.cpp moc_serialconn.cpp moc_serialwin.cpp moc_qcustomplot.cpp moc_savevidthread.cpp moc_detectQR.cpp moc_robottracker.cpp moc_renderarea.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_kilobot.cpp moc_kilobotenvironment.cpp moc_kilobotexperiment.cpp moc_kilobotoverheadcontroller.cpp moc_arenaWindow.cpp moc_envbrain.cpp moc_calibrate.cpp moc_serialconn.cpp moc_serialwin.cpp moc_qcustomplot.cpp moc_savevidthread.cpp moc_detectQR.cpp moc_robottracker.cpp moc_renderarea.cpp
moc_mainwindow.cpp: mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevidthread.h \
		tracker/robottracker.h \
		Kilobot/kilobot.h \
		Kilobot/kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		envbrain.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_kilobot.cpp: Kilobot/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include Kilobot/kilobot.h -o moc_kilobot.cpp

moc_kilobotenvironment.cpp: Kilobot/kilobotenvironment.h \
		Kilobot/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include Kilobot/kilobotenvironment.h -o moc_kilobotenvironment.cpp

moc_kilobotexperiment.cpp: Kilobot/kilobotexperiment.h \
		Kilobot/kilobotenvironment.h \
		Kilobot/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include Kilobot/kilobotexperiment.h -o moc_kilobotexperiment.cpp

moc_kilobotoverheadcontroller.cpp: Kilobot/kilobotoverheadcontroller.h \
		Kilobot/kilobot.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include Kilobot/kilobotoverheadcontroller.h -o moc_kilobotoverheadcontroller.cpp

moc_arenaWindow.cpp: arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include arenaWindow.h -o moc_arenaWindow.cpp

moc_envbrain.cpp: envbrain.h \
		ui/worldmodel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include envbrain.h -o moc_envbrain.cpp

moc_calibrate.cpp: ohc/calibrate.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ohc/calibrate.h -o moc_calibrate.cpp

moc_serialconn.cpp: ohc/serialconn.h \
		ohc/intelhex.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ohc/serialconn.h -o moc_serialconn.cpp

moc_serialwin.cpp: ohc/serialwin.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ohc/serialwin.h -o moc_serialwin.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_savevidthread.cpp: savevidthread.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include savevidthread.h -o moc_savevidthread.cpp

moc_detectQR.cpp: tracker/detectQR.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include tracker/detectQR.h -o moc_detectQR.cpp

moc_robottracker.cpp: tracker/robottracker.h \
		Kilobot/kilobot.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include tracker/robottracker.h -o moc_robottracker.cpp

moc_renderarea.cpp: ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jetsi/projects/LARS/LARS/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jetsi/projects/LARS/LARS -I/usr/local/include/opencv4 -I/usr/include/boost -I/opt/pylon/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/aarch64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/aarch64-linux-gnu/11/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include ui/renderarea.h -o moc_renderarea.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_DynamicWidgets.h ui_arenaWindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		qcustomplot.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_DynamicWidgets.h: DynamicWidgets.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DynamicWidgets.ui -o ui_DynamicWidgets.h

ui_arenaWindow.h: arenaWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic arenaWindow.ui -o ui_arenaWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevidthread.h \
		tracker/robottracker.h \
		Kilobot/kilobot.h \
		Kilobot/kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		envbrain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

kilobot.o: Kilobot/kilobot.cpp Kilobot/kilobot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kilobot.o Kilobot/kilobot.cpp

kilobotoverheadcontroller.o: Kilobot/kilobotoverheadcontroller.cpp Kilobot/kilobotoverheadcontroller.h \
		Kilobot/kilobot.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		ohc/packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kilobotoverheadcontroller.o Kilobot/kilobotoverheadcontroller.cpp

arenaWindow.o: arenaWindow.cpp arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		ui_arenaWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arenaWindow.o arenaWindow.cpp

envbrain.o: envbrain.cpp envbrain.h \
		ui/worldmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o envbrain.o envbrain.cpp

publicvars.o: etc/publicvars.cpp etc/publicvars.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o publicvars.o etc/publicvars.cpp

calibrate.o: ohc/calibrate.cpp ohc/calibrate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrate.o ohc/calibrate.cpp

intelhex.o: ohc/intelhex.cpp ohc/intelhex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o intelhex.o ohc/intelhex.cpp

serialconn.o: ohc/serialconn.cpp ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialconn.o ohc/serialconn.cpp

serialwin.o: ohc/serialwin.cpp ohc/serialwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialwin.o ohc/serialwin.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		etc/publicvars.h \
		qcustomplot.h \
		savevidthread.h \
		tracker/robottracker.h \
		Kilobot/kilobot.h \
		Kilobot/kilobotoverheadcontroller.h \
		ohc/serialwin.h \
		ohc/serialconn.h \
		ohc/intelhex.h \
		ohc/calibrate.h \
		arenaWindow.h \
		ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h \
		envbrain.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

savevidthread.o: savevidthread.cpp savevidthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o savevidthread.o savevidthread.cpp

detectQR.o: tracker/detectQR.cpp tracker/detectQR.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detectQR.o tracker/detectQR.cpp

pylon.o: tracker/pylon.cpp tracker/pylon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pylon.o tracker/pylon.cpp

robottracker.o: tracker/robottracker.cpp tracker/robottracker.h \
		Kilobot/kilobot.h \
		tracker/pylon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robottracker.o tracker/robottracker.cpp

voronoiGenerator.o: ui/geom/voronoiGenerator.cpp ui/geom/voronoiGenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o voronoiGenerator.o ui/geom/voronoiGenerator.cpp

renderarea.o: ui/renderarea.cpp ui/renderarea.h \
		ui/worldmodel.h \
		ui/geom/voronoiGenerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderarea.o ui/renderarea.cpp

worldmodel.o: ui/worldmodel.cpp ui/worldmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worldmodel.o ui/worldmodel.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_kilobot.o: moc_kilobot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobot.o moc_kilobot.cpp

moc_kilobotenvironment.o: moc_kilobotenvironment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobotenvironment.o moc_kilobotenvironment.cpp

moc_kilobotexperiment.o: moc_kilobotexperiment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobotexperiment.o moc_kilobotexperiment.cpp

moc_kilobotoverheadcontroller.o: moc_kilobotoverheadcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kilobotoverheadcontroller.o moc_kilobotoverheadcontroller.cpp

moc_arenaWindow.o: moc_arenaWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_arenaWindow.o moc_arenaWindow.cpp

moc_envbrain.o: moc_envbrain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_envbrain.o moc_envbrain.cpp

moc_calibrate.o: moc_calibrate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrate.o moc_calibrate.cpp

moc_serialconn.o: moc_serialconn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialconn.o moc_serialconn.cpp

moc_serialwin.o: moc_serialwin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialwin.o moc_serialwin.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_savevidthread.o: moc_savevidthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_savevidthread.o moc_savevidthread.cpp

moc_detectQR.o: moc_detectQR.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detectQR.o moc_detectQR.cpp

moc_robottracker.o: moc_robottracker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robottracker.o moc_robottracker.cpp

moc_renderarea.o: moc_renderarea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_renderarea.o moc_renderarea.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

